### ISSUE TITLE
combining with piggy ce dosnt work correctly

### ISSUE THREAD

**Issue by TheUtopianPlayz** [ItsGabry/NanoCombiner#2]
combining with vanilla enchants works fine, but with piggy ce 95% percent of the time it dosnt dcombine the ce's right even know the ce's are compatible, and most of the time only keeps the ces from 1 of the swords, 

side notes ik the plugin is new but a better gui layout would be good, try using the hopper inventory instead of a normal chest, and naming the red glass panes as a space so they are blank and the green  as confirm, and also a preview of the finished item would be cool as well, similar to how anvils work
i would start with the hopper inventory and the pane naming 1st

**Comment by ItsGabry** [comment]
have you installed the latest version on poggit?

**Comment by TheUtopianPlayz** [comment]
if u mean the released build 12, then yes 

i really like the concept and would love to use it on my server, once the bug is fixed

**Comment by ItsGabry** [comment]
I will check the problem even if I understand why, within this week I will release a bug fix. sorry if I can't do it right away.

**Comment by TheUtopianPlayz** [comment]
its fine ty

**Comment by ItsGabry** [comment]
sorry, are you using the latest version of piggycustomenchant and the plugin? the problem doesn't happen to me, can you send me a video of the problem?

**Comment by TheUtopianPlayz** [comment]
i migtht be using a dev build

**Comment by TheUtopianPlayz** [comment]
i switched to the released build and it worked fine, i knowticed that lifesteal 2 and lifesteal 2 make lifesteal 4 tho

**Comment by TheNewHEROBRINEX** [comment]
That's how @ItsGabry decided the plugin to work like. I opened an issue (#7) suggesting to add the possibility to sum to the increment by 1 method instead of the current one.
Anyway, I'm closing this issue since you said that after updating PiggyCustomEnchants the plugin is working fine.
