### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [ItsGabry/NanoCombiner#9]
If you got vanilla enchantments such as efficiency 15 and u try combine with efficiency 5, it doesnt make it eff 20

**Comment by TheNewHEROBRINEX** [comment]
What do you get instead?

**Comment by BroCrows** [comment]
It makes Efficiency 5, im having same problem, I put a suggestion in #6

**Comment by ItsGabry** [comment]
yours is not a problem. you cannot enchant beyond the maximum level of the enchantment itself
